#!/usr/bin/env python3
"""Verify the registry's data and tooling files against
checksums.json, generated by tools/generate_checksums.py.

Exit code 0 if every listed file matches its recorded checksum.
Exit code 1 if checksums.json is missing, any file is missing, or
any checksum mismatches.

Usage:
  python3 tools/verify_checksums.py
"""
import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "checksums.json"


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    if not MANIFEST_PATH.is_file():
        print(
            f"ERROR: {MANIFEST_PATH.name} not found. "
            f"Run tools/generate_checksums.py first.",
            file=sys.stderr,
        )
        return 1

    with open(MANIFEST_PATH) as f:
        manifest = json.load(f)

    if manifest.get("algorithm") != "sha256":
        print(
            f"ERROR: unsupported algorithm '{manifest.get('algorithm')}' "
            f"in {MANIFEST_PATH.name}",
            file=sys.stderr,
        )
        return 1

    files = manifest.get("files", {})
    if not files:
        print(f"ERROR: {MANIFEST_PATH.name} lists no files.", file=sys.stderr)
        return 1

    missing = []
    mismatched = []
    verified = 0

    for rel_path, expected in sorted(files.items()):
        full_path = REPO_ROOT / rel_path
        if not full_path.is_file():
            missing.append(rel_path)
            continue
        actual = sha256_of(full_path)
        if actual != expected:
            mismatched.append((rel_path, expected, actual))
        else:
            verified += 1

    if missing:
        print(f"MISSING ({len(missing)}):", file=sys.stderr)
        for m in missing:
            print(f"  - {m}", file=sys.stderr)

    if mismatched:
        print(f"MISMATCHED ({len(mismatched)}):", file=sys.stderr)
        for rel_path, expected, actual in mismatched:
            print(f"  - {rel_path}", file=sys.stderr)
            print(f"      expected: {expected}", file=sys.stderr)
            print(f"      actual:   {actual}", file=sys.stderr)

    if missing or mismatched:
        print(
            f"\nFAILED: {verified} verified, {len(missing)} missing, "
            f"{len(mismatched)} mismatched",
            file=sys.stderr,
        )
        return 1

    print(f"OK: {verified}/{verified} file(s) verified against {MANIFEST_PATH.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
